# Generated by Django 4.1.7 on 2023-03-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopSellingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('number_sold', models.FloatField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
