# Generated by Django 4.1.7 on 2023-03-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile_Details',
        ),
    ]
